// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bean.proto

package bank_common

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BaseRequest struct {
	ReqBody              string   `protobuf:"bytes,1,opt,name=reqBody,proto3" json:"reqBody,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseRequest) Reset()         { *m = BaseRequest{} }
func (m *BaseRequest) String() string { return proto.CompactTextString(m) }
func (*BaseRequest) ProtoMessage()    {}
func (*BaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_93037caa5acc296f, []int{0}
}

func (m *BaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseRequest.Unmarshal(m, b)
}
func (m *BaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseRequest.Marshal(b, m, deterministic)
}
func (m *BaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseRequest.Merge(m, src)
}
func (m *BaseRequest) XXX_Size() int {
	return xxx_messageInfo_BaseRequest.Size(m)
}
func (m *BaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BaseRequest proto.InternalMessageInfo

func (m *BaseRequest) GetReqBody() string {
	if m != nil {
		return m.ReqBody
	}
	return ""
}

type BaseReply struct {
	RespBody             string   `protobuf:"bytes,1,opt,name=respBody,proto3" json:"respBody,omitempty"`
	ErrorCode            string   `protobuf:"bytes,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	ErrorDes             string   `protobuf:"bytes,3,opt,name=errorDes,proto3" json:"errorDes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseReply) Reset()         { *m = BaseReply{} }
func (m *BaseReply) String() string { return proto.CompactTextString(m) }
func (*BaseReply) ProtoMessage()    {}
func (*BaseReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_93037caa5acc296f, []int{1}
}

func (m *BaseReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseReply.Unmarshal(m, b)
}
func (m *BaseReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseReply.Marshal(b, m, deterministic)
}
func (m *BaseReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseReply.Merge(m, src)
}
func (m *BaseReply) XXX_Size() int {
	return xxx_messageInfo_BaseReply.Size(m)
}
func (m *BaseReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseReply.DiscardUnknown(m)
}

var xxx_messageInfo_BaseReply proto.InternalMessageInfo

func (m *BaseReply) GetRespBody() string {
	if m != nil {
		return m.RespBody
	}
	return ""
}

func (m *BaseReply) GetErrorCode() string {
	if m != nil {
		return m.ErrorCode
	}
	return ""
}

func (m *BaseReply) GetErrorDes() string {
	if m != nil {
		return m.ErrorDes
	}
	return ""
}

func init() {
	proto.RegisterType((*BaseRequest)(nil), "bank_common.BaseRequest")
	proto.RegisterType((*BaseReply)(nil), "bank_common.BaseReply")
}

func init() { proto.RegisterFile("bean.proto", fileDescriptor_93037caa5acc296f) }

var fileDescriptor_93037caa5acc296f = []byte{
	// 173 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x4a, 0x4d, 0xcc,
	0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4e, 0x4a, 0xcc, 0xcb, 0x8e, 0x4f, 0xce, 0xcf,
	0xcd, 0xcd, 0xcf, 0x53, 0x52, 0xe7, 0xe2, 0x76, 0x4a, 0x2c, 0x4e, 0x0d, 0x4a, 0x2d, 0x2c, 0x4d,
	0x2d, 0x2e, 0x11, 0x92, 0xe0, 0x62, 0x2f, 0x4a, 0x2d, 0x74, 0xca, 0x4f, 0xa9, 0x94, 0x60, 0x54,
	0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x71, 0x95, 0x12, 0xb9, 0x38, 0x21, 0x0a, 0x0b, 0x72, 0x2a, 0x85,
	0xa4, 0xb8, 0x38, 0x8a, 0x52, 0x8b, 0x0b, 0x90, 0xd4, 0xc1, 0xf9, 0x42, 0x32, 0x5c, 0x9c, 0xa9,
	0x45, 0x45, 0xf9, 0x45, 0xce, 0xf9, 0x29, 0xa9, 0x12, 0x4c, 0x60, 0x49, 0x84, 0x00, 0x48, 0x27,
	0x98, 0xe3, 0x92, 0x5a, 0x2c, 0xc1, 0x0c, 0xd1, 0x09, 0xe3, 0x1b, 0xb9, 0x70, 0x31, 0x87, 0x54,
	0xe4, 0x09, 0xd9, 0x72, 0xb1, 0x83, 0x6c, 0x02, 0x31, 0x25, 0xf4, 0x90, 0xdc, 0xaa, 0x87, 0xe4,
	0x50, 0x29, 0x31, 0x2c, 0x32, 0x05, 0x39, 0x95, 0x4a, 0x0c, 0x49, 0x6c, 0x60, 0x5f, 0x1a, 0x03,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x87, 0x7e, 0x59, 0xc0, 0xf3, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TxnClient is the client API for Txn service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TxnClient interface {
	BaseTxn(ctx context.Context, in *BaseRequest, opts ...grpc.CallOption) (*BaseReply, error)
}

type txnClient struct {
	cc *grpc.ClientConn
}

func NewTxnClient(cc *grpc.ClientConn) TxnClient {
	return &txnClient{cc}
}

func (c *txnClient) BaseTxn(ctx context.Context, in *BaseRequest, opts ...grpc.CallOption) (*BaseReply, error) {
	out := new(BaseReply)
	err := c.cc.Invoke(ctx, "/bank_common.Txn/BaseTxn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TxnServer is the server API for Txn service.
type TxnServer interface {
	BaseTxn(context.Context, *BaseRequest) (*BaseReply, error)
}

func RegisterTxnServer(s *grpc.Server, srv TxnServer) {
	s.RegisterService(&_Txn_serviceDesc, srv)
}

func _Txn_BaseTxn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TxnServer).BaseTxn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bank_common.Txn/BaseTxn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TxnServer).BaseTxn(ctx, req.(*BaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Txn_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bank_common.Txn",
	HandlerType: (*TxnServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BaseTxn",
			Handler:    _Txn_BaseTxn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bean.proto",
}
