package qrcode

import (
	"fmt"
	"testing"
)

func TestDecodeEmvQR(t *testing.T) {
	demoDataList := []string{
		"hQVDUFYwMWFkTwigAAAAJQEQAVcTN0JFABchAJ0kEiARcREjRQAAD58IAgAQYz6fJggcgXR2YgY/hJ82AgABXzQBAJ83BKVqkFKfECAfAREDoAEAARAZAQEAAAEjEjEjI1lGIHeXAQESNFZ4kA==",
		"hQVDUFYwMWFfTwigAAAAJQEQAVoIN0JFABchAJ9fJAMkEjGfCAIAEGM+nyYI7YYX9qGAA7mfNgIAAV80AQOfNwTom1OTnxAgHwERA6ABAAEQGQEBAAABIxIxIyNZnk+bsgEDEjRWeJA=",
		"hQVDUFYwMWFkTwigAAAAJQEQAVcTN0JFABchAJ0kEiARcREjRQAAD58IAgAQYz6fJgjqiYQYx91zc582AgABXzQBA583BMA7WWefECAfAREDogEAARAZAQEAAAEjEjEjI1meT5uyAQUSNFZ4kA==",
		"hQVDUFYwMWFRTwigAAAAJQEQAVcTN0JFABchAJ0kEiARcREjRQAAD58IAgAQXy0CZW5jJp8mCCxWdcrubYa2nzYCAAFfNAEDnzcE51xmCJ8QCAcBEQOgAQAC",
		"hQVDUFYwMWFuTwigAAAAJQEQAVoIN0JFABchAJ9fJIEDJBIxnwiCAAIAEF8gCUFNRVgvVEVTVGM+nyYIZgAc/lKYv+SfNgIAAV80AQOfNwTpCnBjnxAgHwERA6ABAAEQGQEBAAABJBIxIyNZHWyR9AEDEjRWeJBlggEFn2iCAQD/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////",
		"hQVDUFYwMWGB/08IoAAAACUBEAFXEzdCRQAXIQCdJBIgEXERI0UAAA+fCAIAEFAOQU1FWCBURVNUIENQMDZfLQJlbl9QJm1haWx0bzphbWVyaWNhbmV4cHJlc3NjdXN0b21lckBvcmcuY29tnxkGASNFZ4kBnyQdQVhQLTEyMzQ1Njc4OTBBQkNERUZHSElKSy1YWVqfJQIJIWNtnyYIbc/Fb6g6b3yfNgIAAV80AQOfNwSwbHY0nxAgHwERA6ABAAEQGQEBAAABIxIxIyNZnk+bsgEDEjRWeJCCAgAAlQWAAAAAAJ8CBgAAAAABAJ8DBgAAAAAAAJ8aAgYIXyoCBgiaAxQBAZwBAA==",
		"hQVDUFYwMWFkTwigAAAAJQEQAVcTN0JFABchAJ0kEiARcREjRQAAD58IAgAQYz6fNwSxLokknyYIjP8uRoNyOrOfNgIAAV80AQOfECAfAREDoAEAARAZAQEAAAEjEjEjI1meT5uyAQMSNFZ4kGVDn2hAQUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVphYmNkZWZnaGlqa2xtbm9wcXJzdHV2d3h5ejAxMjM0NTY3ODkrL2UDn2gAZYGCn2h//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////w==",
		"hQVDUFYwMWFkTwigAAAAJQEQAVcTN0JFABchAJ0kEiARcREjRQAAD58IAgAQYz5fNAEDnyYIoWombdi7wxyfNgIAAZ83BKd6lIKfECAfAREDoAEAARAZAQEAAAEjEjEjI1meT5uyAQMSNFZ4kGUAZX+faHz/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////ZYGAn2h9//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////9lCp9oB/////////8=",
		"ZQCFBUNQVjAxYU5PCKAAAAAlARABVxM3QkUAFyEAnSQSIBFxESNFAAAPnwgCABBjKJ8mCDQQ8y3iiubJnzYCAAFfNAEDnzcE4B4CFJ8QCgkBEQOgAQAC//8=",
		"hQVDUFYwMWUAYU5PCKAAAAAlARABVxM3QkUAFyEAnSQSIBFxESNFAAAPnwgCABBjKJ8mCJs9ZthTUfBdnzYCAAFfNAEDnzcEsXoROJ8QCgkBEQOgAQAC//8=",
		"hQVDUFYwMWFZTwigAAAAJQEQAVoIN0JFABchAJ+fCAIAEGM+nyYIPiJ/motEOrGfNgIAAV80AQOfNwTpGxVXnxAgHwERA6IBAAEQGQEBAAABIxIxIyNZnk+bsgEFEjRWeJA=",
		"hQVDUFYwMWE8TwigAAAAJQEQAVoIN0JFABchAJ9fJAMkEjGfCAIAEGMbnyYI0T6F0nnN25SfNgIAAV80AQOfNwTZCxiH",
		"hQVDUFYwMWEfTwigAAAAJQEQAVoIN0JFABchAJ9fJAMkEjGfCAIAEGM+nyYIT1iEegVgJvefNgIAAV80AQOfNwTXXCKJnxAgHwERA6ABAAEQGQEBAAABIxIxIyNZnk+bsgEDEjRWeJA=",
		"hQVDUFYwMWGB/1oIN0JFABchAJ9fJAMkEjGfCAIAEFAOQU1FWCBURVNUIENQMTRfLQJlbl9QF21haWx0bzpjb250YWN0QGFleHAuY29tXyARSmFuZSBTYWlsb3IgU21pdGifGQYBI0VniQGfJB1BWFAtMTIzNDU2Nzg5MEFCQ0RFRkdISUpLLVhZWp8lAgkhY22fNgIAAV80AQOfNwSnjSUZnxAgHwERA6ABAAEQGQEBAAABIxIxIyNZnk+bsgEDEjRWeJCCAgAAlQWAAAAAAJ8CBgAAAAABAJ8DBgAAAAAAAJ8aAgAAXyoCAACaAxQBAZwBAJ8mCIvKkkrMjBa4TwigAAAAJQEQAQ==",
		"HQVDUFYwMWFkTwigAAAAJQEQAVcTN0JFABchAJ0kEiARcREjRQAAD58IAgAQYz6fJggyz5/MstfHrJ82AgABXzQBA583BKNqKUifECAfAREDoAEAARAZAQEAAAEjEjEjI1meT5uyAQMSNFZ4kA==",
		"hQVDUFYwMWFfTwigAAAAJQEQAVoIN0JFABchAJ9fJAMkEjGfCAL//2M+nyYI4ehQp1dJ9xifNgIAAV80AQOfNwTTOjIAnxAgHwERA6ABAAEQGQEBAAABIxIxIyNZnk+bsgEDEjRWeJA=",
		"hQVDUFYwMWGBrU8IoAAAACUBEAFXEzdCRQAXIQCdJBIgEXERI0UAAA+fCAIAEFAQQU1FUklDQU4gRVhQUkVTU18tCHBoZXNkZWVuX1ApYW1lcmljYW5leHByZXNzY3VzdG9tZXJlbWFpbGlkQGRvbWFpbi5jb21jPp8mCOUHjJhnrD5+nzYCAAFfNAEDnzcEwTo1Mp8QIB8BEQQAAAABEBkBAQAAASMSMSMjWZ5Pm7IBAxI0VniQ",
		"hQVDUFYwMWFLTwegAAAAACAYVxISNFZ4kBI9JBIgEXERI0UAAA9QBkVNVkNvLl8tAmVuXyAKRU1WQ08vVEVTVGMSnyYIVKJC406gaoSfNwTjLUgHYWBPCKAAAAAlARABWgg0ERFZckJRP18kAyQSMZ8IAgAQUBBBTUVSSUNBTiBFWFBSRVNTXy0CcGhjKJ8mCCGZl0scUZFpnzYCAAFfNAEDnzcEo5xIEJ8QCgkBEQOgAQAB//8=",
		//"hQVDUFYwMWGC1DFPCKAAAAAlARABWgg3QkUAFyEAn18kAyQSMZ8IAgAQYz6fJgh06kCJW7UtuJ82AgABXzQBA583BKJqVmGfECAfAREDoAEAARAZAQEAAAEjEjEjI1meT5uyAQMSNFZ4kA==",
		"hQVEUFYwMWFfTwigAAAAJQEQAVoIN0JFABchAJ9fJAMkEjGfCAIAEGM+nyYIssSNJiurCsafNgIAAV80AQOfNwSzmliXnxAgHwERA6ABAAEQGQEBAAABIxIxIyNZnk+bsgEDEjRWeJA=",
		"hQVDUFYwMWVfTwigAAAAJQEQAVoIN0JFABchAJ9fJAMkEjGfCAIAEGM+nyYImxUP9ZaTmQmfNgIAAV80AQOfNwTTfmCXnxAgHwERA6ABAAEQGQEBAAABIxIxIyNZnk+bsgEDEjRWeJBlggEDn2iB/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////w==",
		"hQVDUFYwMWFUTwigAAAAJQEQAVcTN0JFABchAJ0kEiARcREjRQAAD58IAgAQUAFDXy0CcGhjJp8mCEyJ6PROI6aenzYCAAFfNAEDnzcE4ExieJ8QCAcBEQOgAQAC",
		"hQVDUFYwMWGCAGBjgT6fJgjpjHO2U6lTxp82AgABXzQBA583BLQraZifECAfAREDoAEAARAZAQEAAAEjEjEjI1meT5uyAQMSNFZ4kE8IoAAAACUBEAFaCDdCRQAXIQCfXyQDJBIxnwgCABA=",
		"hQVDUFYwMWGBhwAAAABPCKAAAAAlARABVxM3QkUAFyEAnSQSIBFxESNFAAAPnwgCABAAAAAAUBBBTUVSSUNBTiBFWFBSRVNTXy0CZW4AAAAAYz6fJgiLU/38uvgQWZ82AgABXzQBA583BMBqcwGfECAfAREDoAEAARAZAQEAAAEjEjEjI1meT5uyAQMSNFZ4kA==",
		"hQVDUFYwMWFeTwugAAAAJQEgGAEjRVcTN0JFABchAJ0kEiARcREjRQAAD58IAgAQUAZBTUVYIDFfLQJlbmMonyYIPhx0/AXVrB2fNgIAAV80AQOfNwSxG3eHnxAKCQERA6ABAAL//2FUTwigAAAAJQEgGFoINBERWXJCUT9fJAMkEjGfCAIAEFAGQU1FWCAyXy0CcGhjJp8mCC/AUo+ef6uanzYCAAFfNAEDnzcEpjp3kJ8QCAcBEQOgAQAC",
		"hQVDUFYwMWFpTwigAAAAJQEQAVoIN0JFABchAJ9aCDdCRQAXIQCfXyQDJBIxnwgCABBjPp8mCF5G6FzR7VfpnzYCAAFfNAEDnzcEsJuRBZ8QIB8BEQOgAQABEBkBAQAAASMSMSMjWZ5Pm7IBAxI0VniQ",
		"hQVDUFYwMWF2TwigAAAAJQEQAVoIN0JFABchAJ9fJAMkEjGfCAIAEFAQQU1FUklDQU4gRVhQUkVTU18tAmVuYz6fJghSnuzOjhWfk582AgABXzQBAZ83BLCOlSWfECAfAREDoAEAARAZAQEAAAEjEjEjI1lmTyq2AQMSNFZ4kA==",
		"hQVDUFYwMWFfTwigAAAAJQEQAVcTN0JFABchAJ0kEiARcREjRQAAD2M+nyYIBa6eT5zQeg2fNgIAAV80AQOfNwTmnCWUnxAgHwERA6ABAAEQGQEBAAABIxIxIyNZnk+bsgEDEjRWeJA=",
		"hQVDUFYwMWGBhk8IoAAAACUBEAFXEzdCRQAXIQCdJBIgEXERI0UAAA+fCAIAEFAQQU1FUklDQU4gRVhQUkVTU18tCHBoZnJlbmlknyUCCSFjPp8mCCLQpbIIakOZnzYCAAFfNAEDnzcEuF1HF58QIB8BEQOgAQABEBkBAQAAASMSMSMjWZ5Pm7IBAxI0VniQ",
		"hQVDUFYwMWGBgE8IoAAAACUBEAFXEzdCRQAXIQCdJBIgEXERI0UAAA+fCAIAEFAQQU1FUklDQU4gRVhQUkVTU18tAnBonyUCCSFjPp8mCPX/J1s6yK8VnzYCAAFfNAEDnzcE51pIlJ8QIB8BEQOgAQABEBkBAQAAASMSMSMjWZ5Pm7IBAxI0VniQ",
		"hQVDUFYwMWGBy08IoAAAACUBEAFXEzdCRQAXIQCdJBIgEXERI0UAAA+fCAIAEFAQQU1FUklDQU4gRVhQUkVTU18tAnBoX1AobWFpbHRvOkFtZXJpY2FuLkV4cHJlc3MuQ29udGFjdEBhZXhwLmNvbZ8kHUFYUC0xMjM0NTY3ODkwQUJDREVGR0hJSkstWFlanyUCCSFjPp8mCAA0nGwVTp0ZnzYCAAFfNAEDnzcE0C5Qhp8QIB8BEQOgAQABEBkBAQAAASMSMSMjWZ5Pm7IBAxI0VniQ",
		"hQVDUFYwMWGBt08IoAAAACUBEAFXEzdCRQAXIQCdJBIgEXERI0UAAA+fCAIAEFAQQU1FUklDQU4gRVhQUkVTU18tAnBoX1AUdGVsOis2My0wMDAtMTExLTAwMDCfJB1BWFAtMTIzNDU2Nzg5MEFCQ0RFRkdISUpLLVhZWp8lAgkhYz6fJggsUGWOtzW8/582AgABXzQBA583BNY9UnefECAfAREDoAEAARAZAQEAAAEjEjEjI1meT5uyAQMSNFZ4kA==",
		"hQVDUFYwMWGBwE8IoAAAACUBEAFXEzdCRQAXIQCdJBIgEXERI0UAAA+fCAIAEFAQQU1FUklDQU4gRVhQUkVTU18tAmVuXyAUVEVTVC9BTUVYIENBUkRIT0xERVKfGQYBI0VniQGfJB1BWFAtMTIzNDU2Nzg5MEFCQ0RFRkdISUpLLVhZWp8lAgkhYz6fJghs2ToRHpoTep82AgABXzQBA583BLUqVECfECAfAREDoAEAARAZAQEAAAEjEjEjI1meT5uyAQMSNFZ4kA==",
		"hQVDUFYwMWFTTwigAAADMwEBAVcOYhYmEAAAAAJIXVASIB9jM4ICAACfEBEHAQEDoAAAAQg5MDg4MDAxOZ8mCFZsYec5bDImnycBgJ82ApBbnzcEQjV2yF80AQE",
	}

	for _, demoData := range demoDataList {
		content, err := DecodeEmvQR(demoData)
		if err != nil {
			fmt.Println("parse fail ->", demoData)
			t.Error(err)
			return
		}

		fmt.Println("content->", content)
	}

}
